### PR TITLE
Milestone 2 (Create) done!

### PR DESCRIPTION
**Pull request by danapham**
## Description
- all the modules have a create button that launches a form and adds the data to firebase

## Related Issue
n/a

## Motivation and Context
we need to be able to add data before we do anything with it

## How Can This Be Tested?
- go to our [deployed site](https://jurassic-world-eb567.web.app/)
- try entering things into each form 
- every form should capture the data and send to our firebase (you should have gotten an email giving you access)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by drteresavasquez** [comment]
One small thing on this PR. The mobile nav is not working.

**Review by drteresavasquez — CHANGES_REQUESTED** [review]
Fix mobile nav

**Review by brownabs — APPROVED** [review]
looks good!

**Comment by brownabs** [comment]
Looks good! Approved.

**Review by drteresavasquez — APPROVED** [review]
Ticket created for navbar for the issue, so move forward.

**Pull request merged**
