### PR TITLE
added edit staff

### PR DESCRIPTION
**Pull request by DeannaMix**
## Description
Users can now edit staff

## Related Issue
#21 

## Motivation and Context
The user wanted to be able to edit the staff members

## How Can This Be Tested?
git fetch origin editStaff

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Review by danapham — APPROVED** [review]
nice job!

**Review by michaelpfohl — CHANGES_REQUESTED** [review]
getting the following error when attempting to edit a staff member right after adding: 

```
TypeError: Cannot read property 'name' of null
   at eval (editStaffForm.js?db31:43)

**Review by bandstrar — CHANGES_REQUESTED** [review]
The Edit button is populating and working for unauthed users, and the Add Staff button should be disabled when editing a staff member

**Review by bandstrar — APPROVED** [review]
Looks great!

**Review by michaelpfohl — APPROVED** [review]
approved!

**Pull request merged**
