### PR TITLE
Rm chaos

### LINKED ISSUE #97: Milestone 2 - Review
# User Story
- As a user, I should be shown a toast whenever the Chaos Monkey strikes
- As a user, I should allow the Chaos Monkey to do one random act for a set interval, 10 seconds
- As a user, the Chaos Monkey should have a chance to break down a random ride
- As a user, the Chaos Monkey should have a chance to kidnap a random staff member
- As a user, the Chaos Monkey should have a chance to break a random piece of equipment

# Acceptance Criteria
WHEN the user logs in
THEN they should see a Chaos Monkey button
AND when it's clicked a toast will appear
AND they will see a random action that the bad monkey did

## Link to deployed site:
[Click Here](https://nutshell-part-two.web.app/)

# Dependencies
#32 
#92 
#93 
#94

### PR DESCRIPTION
**Pull request by ryanmcnair**
## Description

closes #97 

## Motivation and Context
closing issue ticket

### CODE REVIEW

**Review by smudick — APPROVED** [review]
!!

**Review by smudick — APPROVED** [review]
!!

**Review by Jonathon22 — APPROVED** [review]
Reviewing the code for issue #97 The code looks spectacular

**Review by BaileyEDennis — APPROVED** [review]
Reviewed code, all good

**Pull request merged**
